apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: lamia-ingress
 namespace: lamia
 annotations:
   kubernetes.io/ingress.class: traefik
   cert-manager.io/issuer: "lamia-issuer"
spec:
 tls:
   - hosts:
       - lamia.goldenhandsoftware.co.uk
     secretName: lamia-ingress-http-tls
 rules:
   - host: lamia.goldenhandsoftware.co.uk
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: lamia-svc
               port:
                 number: 80